---
- hosts: proxy
  user: root
  tasks:
    - name: restart proxy server
      shell: swift-init proxy restart
    - name: restart memcache server
      service: name=memcached state=restarted
      
- hosts: container
  user: root
  tasks:
    - name: restart container services
      shell: swift-init {{ item }} restart
      with_items:
        - container-server
        - container-auditor
        - container-replicator
        - container-reconciler 
        - container-updater

- hosts: account
  user: root
  tasks:
    - name: restart account services
      shell: swift-init {{ item }} restart
      with_items:
        - account-server
        - account-auditor
        - account-reaper
        - account-replicator

- hosts: object
  user: root
  tasks:
    - name: restart object services
      shell: swift-init {{ item }} restart
      with_items:
        - object-server
        - object-auditor
        - object-replicator
        - object-updater
