---
- name: "Install liberasurecode dependencies (Debian/Ubuntu)"
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items: "{{ liberasurecode_packages.debian }}"
  when: ansible_os_family == 'Debian'

- name: "Install liberasurecode dependencies (RedHat)"
  yum: pkg={{ item }} state=installed 
  with_items: "{{ liberasurecode_packages.redhat }}"
  when: ansible_os_family == 'RedHat'
  
- name: "Checkout liberasurecode git repo"
  git: repo={{ liberasurecode_git_repo }} version={{ liberasurecode_git_tag }} dest=/opt/swift/liberasurecode update=yes

- name: "Rebuild liberasurecode"
  shell: "./autogen.sh && ./configure && make && make install"
  args:
    chdir: /opt/swift/liberasurecode

- name: add path to /etc/ld.so.conf
  lineinfile: dest=/etc/ld.so.conf line="/usr/local/lib"

- name: run ldconfig
  shell: ldconfig