- name: "Setup hosts file"
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" state=present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: groups['all']

# If target is a debian/ubuntu system
- include: debian.yml
  when: ansible_os_family == 'Debian'

# If target is a centos/redhat system
- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: install python modules with pip
  pip: name={{ item }} state=present extra_args='--upgrade'
  with_items:
    - tox
    - nose
    - xattr
    - git-review
    - coverage
    - Paste
    - pyudev
    - pip
    - setuptools

- include: liberasurecode.yml

- name: "Create swift group"
  group: name={{ user }} state=present system=yes

- name: "Create a swift user"
  user: name={{ user }} state=present shell=/bin/false home=/opt/swift system=yes

- name: "Checkout swift git repo"
  git: repo={{ swift_repo }} version={{ swift_repo_tag }} dest=/opt/swift/swift update=yes
  tags:
    - deploy_code

- name: "Run post git checkout hook"
  shell: "{{ git_post_checkout }}"
  args:
    chdir: /opt/swift/swift 
  when: git_post_checkout is defined 
  tags:
    - deploy_code

- name: install swift's dependencies
  pip: requirements=/opt/swift/swift/requirements.txt
  tags:
    - deploy_code

- name: install swift's test dependencies
  pip: requirements=/opt/swift/swift/test-requirements.txt
  tags:
    - deploy_code

- name: install swift
  command: python setup.py install chdir=/opt/swift/swift
  tags:
    - deploy_code

- name: "Swift directory"
  file: path=/etc/swift owner={{ user }} group={{ user }} state=directory 

- name: "Swift lock directory"
  file: path=/var/lock/swift owner={{ user }} group={{ user }} state=directory 

- name: "Swift log directory - Debain"
  file: path=/var/log/swift owner=syslog group=adm state=directory
  when: ansible_os_family == 'Debian'

- name: "Swift log directory - Redhat"
  file: path=/var/log/swift owner=root group=adm state=directory
  when: ansible_os_family == 'RedHat'

- name: "Setup swift.conf"
  template: src=swift.conf.j2 dest=/etc/swift/swift.conf owner={{ user }} mode=0644

- name: "Set up memchached.conf"
  template: src=memcache.conf.j2 dest=/etc/swift/memcache.conf owner={{ user }} mode=0644
