---
- name: "swift account server configuration"
  template: src=account-server.conf.j2 dest=/etc/swift/account-server.conf owner={{ user }} mode=0644
  notify: 
    - (re)start account server
    - (re)start account auditor
    - (re)start account replicator
    - (re)start account reaper

- name: "Set account server to start at boot"
  cron: special_time=reboot job="swift-init account-server start" name="start swift account server"

- name: "Set account auditor to start at boot"
  cron: special_time=reboot job="swift-init account-auditor start" name="start swift account auditor"

- name: "Set account replicator to start at boot"
  cron: special_time=reboot job="swift-init account-replicator start" name="start swift account replicator"

- name: "Set account reaper to start at boot"
  cron: special_time=reboot job="swift-init account-reaper start" name="start swift account reaper"

- name: "set up rsyslog for account"
  copy: src=10_swift_account.conf dest=/etc/rsyslog.d/10_swift_account.conf owner=root mode=0644 
  notify:
    - restart rsyslog server
