---
swift_common_packages:
  debian:
    - curl
    - python-pip
    - rsync
    - openssh-server
    - git-core
    - python-setuptools
    - python-dev
    - gcc
    - libffi-dev

  redhat:
    - curl
    - collectd
    - influxdb
    - grafana

statsd_host: "::"
statsd_port: 8125
influxdb_host: "127.0.0.1"
influxdb_port: 25826
influxdb_database: collectd
