---
swift_common_packages:
  debian:
    - curl
    - python-pip
    - rsync
    - openssh-server
    - git-core
    - python-setuptools
    - python-dev
    - gcc
    - libffi-dev

  redhat:
    - curl
    - gcc
    - rsync
    - git-core
    - python-setuptools
    - python-pip
    - sqlite
    - xfsprogs
    - git
    - libffi-devel
    - xinetd
    - python-devel
    - python-simplejson
    - pyxattr
    - python-eventlet
    - python-greenlet
    - python-netifaces
    - python-dns
    - python-mock
    - tree
    - vim
    - make
    - autoconf
    - automake
    - libtool
    - openssl-devel
    - sysstat

liberasurecode_git_repo: 'https://github.com/openstack/liberasurecode'
liberasurecode_git_tag: 'master'
liberasurecode_packages:
  debian:
    - build-essential
    - autoconf
    - automake
    - libtool

  redhat:
    - gcc
    - make 
    - autoconf
    - automake
    - libtool
