---
swift_common_packages:
  debian:
    - curl
    - python-pip
    - rsync
    - openssh-server
    - git-core
    - python-setuptools
    - python-dev
    - gcc
    - libffi-dev

  redhat:
    - curl
    - gcc
    - rsync
    - git-core
    - python-setuptools
    - python-pip
