---
swift_common_packages:
  debian:
    - curl
    - python-pip
    - rsync
    - openssh-server
    - git-core
    - python-setuptools
    - python-dev
    - gcc
    - libffi-dev

  redhat:
    - curl
    - gcc
    - rsync
    - git-core
    - python-setuptools
    - python-pip

liberasurecode_git_repo: 'https://github.com/openstack/liberasurecode'
liberasurecode_git_tag: 'master'
liberasurecode_packages:
  debian:
    - build-essential
    - autoconf
    - automake
    - libtool

  redhat:
    - gcc
    - make 
    - autoconf
    - automake
    - libtool
