---
user: swift
#swift_repo: https://github.com/openstack/swift.git
swift_repo: https://github.com/matthewoliver/swift.git
#swift_repo_tag: master
swift_repo_tag: sharding_trie

swift_common_packages:
  debian:
    - curl
    - python-pip
    - rsync
    - openssh-server
    - git-core
    - python-setuptools
    - python-dev
    - gcc
    - libffi-dev

  redhat:
    - curl
    - gcc
    - rsync
    - git-core
    - python-setuptools
    - python-pip
