---
- name: "swift object server configuration"
  template: src=object-server.conf.j2 dest=/etc/swift/object-server.conf owner={{ user }} mode=0644

- name: "swift object expirer configuration"
  template: src=object-expirer.conf.j2 dest=/etc/swift/object-expirer.conf owner={{ user }} mode=0644

- name: "Set object server to start at boot"
  cron: special_time=reboot job="swift-init object-server start" name="start object server"

- name: "Set object auditor to start at boot"
  cron: special_time=reboot job="swift-init object-auditor start" name="start object auditor"

- name: "Set object replicator to start at boot"
  cron: special_time=reboot job="swift-init object-replicator start" name="start object replicator"

- name: "Set object updater to start at boot"
  cron: special_time=reboot job="swift-init object-updater start" name="start object updator"

- name: "Set object reconstructor to start at boot"
  cron: special_time=reboot job="swift-init object-reconstructor start" name="start object reconstructor"

- name: "set up rsyslog for object"
  copy: src=10_swift_object.conf dest=/etc/rsyslog.d/10_swift_object.conf owner=root mode=0644 
  notify:
    - restart rsyslog server

- name: "Setup rsync"
  template: src=rsyncd.conf.j2 dest=/etc/rsyncd.conf owner=root mode=0644
  notify: 
    - restart rsync server

- name: "Create rsync.d directory"
  file: path=/etc/rsyncd.d state=directory

- name: "Dropping rsyncd object configuration"
  template: src=rsyncd-object.conf.j2 dest=/etc/rsyncd.d/object.conf owner=root mode=0644
  notify: 
    - restart rsync server

- name: "Ensure the /var/cache/swift directory exists"
  file: patch=/var/cache/swift state=directory owner={{ user }}

- name: "Make sure device locations have the correct ownership"
  shell: chown {{ user }} -R {{ drives }}/*
